name: Cron jobs
on:
  schedule:
  - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  lobsterss:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://lobsters-bot.vercel.app/api/index?channels=go&channels=ruby&channels=web&channels=security&channels=programming&channels=networking&channels=linux

